### ISSUE TITLE
'break' statement not in loop or switch statement

### ISSUE THREAD

**Issue by brianyu28** [cs50/help50#123]
```
clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow    test.c  -lcs50 -lm -o test
test.c:21:5: error: 'break' statement not in loop or switch statement
    break;
    ^
```

**Comment by mjopp** [comment]
# clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow    test.c  -lcs50 -lm -o test
    # test.c:21:5: error: 'break' statement not in loop or switch statement
    #    break;
    #    ^
    # https://github.com/cs50/help50/issues/123
    #            
    matches = match(r"'break' statement not in loop or switch statement", lines[0]) 
    if matches:
        response = [
            "The command 'break' should only be used within a loop or within a switch statement. It sounds like you used 'break;' outside of a loop or switch statement in your code on line {} of `{}`.".format(matches.line, matches.file)
        ]
        return (lines[0:1], response)

**Comment by mjopp** [comment]
fix is part of the following pull request

https://github.com/cs50/help50/pull/240
