### ISSUE TITLE
redefinition of function or variable

### ISSUE THREAD

**Issue by brianyu28** [cs50/help50#125]
```
clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow    credit.c  -lcs50 -lm -o credit
credit.c:61:5: error: redefinition of 'type'
int type(string s)
    ^
credit.c:25:5: note: previous definition is here
int type(string s)
    ^
1 error generated.
make: *** [credit] Error 1
```

```
scope.c:33:9: error: redefinition of 'a'
    int a = 0;
        ^
scope.c:30:9: note: previous definition is here
    int a = 4;
        ^
1 error generated.
```

**Comment by mjopp** [comment]
# clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow    credit.c  -lcs50 -lm -o credit
    # credit.c:61:5: error: previous definition is here
    # int type(string s)
    # https://github.com/cs50/help50/issues/125
    #            
    matches = match(r"redefinition of", lines[0]) 
    if matches:
        response = [
            "It looks like you have a redefinition of a variable or function in your code. Please check out line {} of `{}`.".format(matches.line, matches.file)
        ]
        return (lines[0:1], response)

**Comment by mjopp** [comment]
fix is part of the following pull request

https://github.com/cs50/help50/pull/240
