### ISSUE TITLE
help50 mv (and similar)

### ISSUE THREAD

**Issue by brianyu28** [cs50/help50#16]
```
$ touch foo
$ touch bar
$ mv foo bar
mv: overwrite ‘bar’?
```

If someone wanted help understanding the above message, presumably we would want them to be able to execute `help50 mv foo bar` in order to produce the output from the matcher in `mv.py`. 

However, when I actually execute that, I get a `Sorry, not sure how to help!`, and the `mv` command overwrites `bar` without prompting.

My guess is that since we have `mv` aliased to `mv -i`: when `help50` is called, it's running `mv` without the `-i` flag, triggering the overwrite without prompting the user, and then not POSTing any output to help50's server. Can/should we do anything about that?

(I'm getting analogous results with `cp` and `rm`)

**Comment by dmalan** [comment]
Good catch. Does this fix for you? https://github.com/cs50/help50/pull/17

**Comment by dmalan** [comment]
My bad, try https://github.com/cs50/help50/pull/18!
