### ISSUE TITLE
variable-sized object may not be initialized

### ISSUE THREAD

**Issue by brianyu28** [cs50/help50#161]
```
clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow    vigenere.c  -lcs50 -lm -lcrypt -o vigenere
vigenere.c:13:10: error: variable-sized object may not be initialized
    char k[strlen(argv[1])]= (argv[1]);
         ^                   ~~~~~~~~~
1 error generated.
make: *** [vigenere] Error 1
```

```
clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wshadow    final.c  -lcs50 -lm -lcrypt -o final
final.c:30:21: error: variable-sized object may not be initialized
                int encrypt[j] = key[j] - 65;
                    ^            ~~~~~~~~~~~
```

```
clang -ggdb3 -O0 -std=c11 -Wall -Werror -o find find.c helpers.c -lcs50 -lm
helpers.c:72:9: error: variable-sized object may not be initialized
    int TVal[size] = t;
        ^            ~
1 error generated.
make: *** [find] Error 1
```

**Comment by mjopp** [comment]
@dmalan @brianyu28  I would propose the following error message:

```
"Looks like you're trying to initialize a variable-sized array on line {} of `{}`, which isn't possible in C.".format(matches.line, matches.file)
```

Are you happy with it, or should I rephrase it? 
I would like to make a pull-request, if you have no comments on the message...

**Comment by mjopp** [comment]
Here is my attempt to solve this issue:
https://github.com/cs50/help50/pull/239

**Comment by mjopp** [comment]
# $ clang foo.c
    # final.c:30:21: error: variable-sized object may not be initialized;
    # int encrypt[j] = key[j] - 65;
    # https://github.com/cs50/help50/issues/161
    #            
    matches = match(r"variable-sized object may not be initialized", lines[0]) 
    if matches:
        response = [
            "Looks like you're trying to initialize a variable-sized array on line {} of `{}`, which isn't possible in C.".format(matches.line, matches.file)
        ]
        return (lines[0:1], response)

**Comment by mjopp** [comment]
fix is part of the following pull request

https://github.com/cs50/help50/pull/240
