### ISSUE TITLE
use has_caret

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#203]
@brianyu28, in quite a few places, we seem to be assuming that `lines[2]` will have [caret diagnostics](http://clang.llvm.org/diagnostics.html), but that's not necessarily true if `clang` is run with other flags, in which case our code might 500 because of `None` return values. We should probably adopt a paradigm of

```python
if len(lines) > 3 and has_caret(lines[2]):
```

or even combine that? I've added `has_caret` to https://github.com/cs50/help50/blob/master/tools.py.

**Comment by brianyu28** [comment]
`var_extract` (which probably should be named `caret_extract`) and `tilde_extract` are both set to return `None` if they can't extract for some reason (such as if there is no caret). Looking back, I realize that there are some cases where I forgot to check for `None`, I can go back and fix those.

**Comment by dmalan** [comment]
Sounds good. Should those perhaps be at the bottom of `clang.py` instead, where `match` is, since they're `clang`-specific?
