### ISSUE TITLE
support the selection of multiple table rows on /review

### ISSUE THREAD

**Issue by coltonoscopy** [cs50/help50#213]
Should be shift-clickable or command/control-clickable.

**Comment by dmalan** [comment]
Allowing user to select checkbox _i_ and _j_, at which point a JavaScript listener automatically checks _i_+1 through _j_-1 suffices!

**Comment by dmalan** [comment]
All set, https://github.com/cs50/help50/commit/db17d550fe175cf2a70ad2f489cc9df3e59336a2.

CC @brianyu28
