### ISSUE TITLE
use of undeclared identifier 'string'; did you mean 'stdin'?

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#24]
**input:**

```c
#include <stdio.h>

int main(void)
{
    string s = get_string();
    printf("hello, %s\n", s);
}
```

**output:**

```
$ clang buggy1.c
buggy1.c:5:5: error: use of undeclared identifier 'string'; did you mean 'stdin'?
    string s = get_string();
    ^~~~~~
    stdin
/usr/include/stdio.h:168:25: note: 'stdin' declared here
extern struct _IO_FILE *stdin;          /* Standard input stream.  */
                        ^
buggy1.c:5:11: error: expected ';' after expression
    string s = get_string();
          ^
          ;
buggy1.c:5:12: error: use of undeclared identifier 's'
    string s = get_string();
           ^
buggy1.c:5:16: warning: implicit declaration of function 'get_string' is invalid in C99 [-Wimplicit-function-declaration]
    string s = get_string();
               ^
buggy1.c:6:27: error: use of undeclared identifier 's'
    printf("hello, %s\n", s);
                          ^
buggy1.c:5:5: warning: expression result unused [-Wunused-value]
    string s = get_string();
    ^~~~~~
2 warnings and 4 errors generated.
```

**current help but should recognize `string` as needing `c50.h`:**

```
By "undeclared identifier," `clang` means you've used a name `string` which hasn't been defined.
If you mean to use `string` as a variable, make sure to declare it by specifying its type, and check that the variable name is spelled correctly.
```

**Comment by tevinvu** [comment]
I ran my code in Visual Studio code and i got this result
#include <string.h>
#include <stdio.h>


int main(void)
{
    string name =  get_string();
    printf("hello, %s\n", name);
    return 0;
}

and I got this result:
string02.c:6:5: error: use of undeclared identifier 'string'
    string name =  get_string();
    ^
string02.c:7:27: error: use of undeclared identifier 'name'
    printf("hello, %s\n", name);
                          ^
2 errors generated.

How can I fix it? I couldn't use <cs50.h> since i don't have an account to log in

**Comment by enzyme69** [comment]
Same here :(

/usr/include/stdio.h:168:25: note: 'stdin' declared here
extern struct _IO_FILE *stdin;          /* Standard input stream.  */
                        ^
hello.c:5:11: error: expected ';' after expression
    string s = get_string("Name: ");
          ^
          ;
hello.c:5:12: error: use of undeclared identifier 's'
    string s = get_string("Name: ");
           ^
hello.c:5:16: warning: implicit declaration of function 'get_string' is invalid in C99 [-Wimplicit-function-declaration]
    string s = get_string("Name: ");
               ^
hello.c:6:27: error: use of undeclared identifier 's'
    printf("hello, %s\n", s);
                          ^
hello.c:5:5: warning: expression result unused [-Wunused-value]
    string s = get_string("Name: ");
    ^~~~~~
2 warnings and 4 errors generated.
~/workspace/ $ clang hello.c
hello.c:5:5: error: use of undeclared identifier 'String'
    String s = get_string("Name: ");
    ^
hello.c:6:27: error: use of undeclared identifier 's'
    printf("hello, %s\n", s);
                          ^
2 errors generated.
~/workspace/ $

**Comment by imambungo** [comment]
if you want to run the program from your computer instead of the cs50 IDE, you should install the [cs50 library](https://github.com/cs50/libcs50) first, then run this command from terminal: `clang hello.c -o hello -lcs50`.

`-lcs50` is needed to link to the library and make sure you've already included the `<cs50.h>` in your source code.

**Comment by techouse** [comment]
In case any lost souls are wondering how to make this work with CMake using `CMakeLists.txt` check this https://github.com/cs50/libcs50/issues/190

**Comment by skylitik** [comment]
#include <cs50.h>
#include <stdio.h>

int main (void)
{
    string s = GetString();
    printf("Hello %s\n" ,s);
}


out:
hello.c:6:16: warning: implicit declaration of function 'GetString' is invalid in C99 [-Wimplicit-function-declaration]
    string s = GetString();
               ^
hello.c:6:12: warning: incompatible integer to pointer conversion initializing 'string' (aka 'char *') with an expression of type 'int'
      [-Wint-conversion]
    string s = GetString();
           ^   ~~~~~~~~~~~
2 warnings generated.
/tmp/hello-8e89fa.o: In function `main':
hello.c:(.text+0xb): undefined reference to `GetString'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
