### ISSUE TITLE
clang line-breaks errors depending on terminal's width

### ISSUE THREAD

**Issue by kzidane** [cs50/help50#242]
It appears `clang` inserts hard line breaks in error messages depending on terminal's width, which causes `help50` to fail to help even with known error messages.

![help50-wide](https://cloud.githubusercontent.com/assets/7230211/25708238/34fc7b80-30e6-11e7-86e0-ed83c6d0ea39.png)
![help50-narrow](https://cloud.githubusercontent.com/assets/7230211/25708237/34f0095e-30e6-11e7-87ae-27705ba20dd6.png)

Haven't researched the best way to handle yet, but a couple of things that come to mind initially are:

1. [limit](http://releases.llvm.org/3.6.0/tools/clang/docs/UsersManual.html#cmdoption-ferror-limit) errors to one error.
2. figure a pattern (if any) (e.g., start of an error, or specific number of tabs/spaces preceding each complementary line), and merge them into current line, before matching.
3. while matching first line fails, merge next line, and try matching again.

**Comment by dmalan** [comment]
Good catch. How about this? https://github.com/cs50/help50/pull/243

Fortunately, `clang` seems to use 6 spaces for broken lines, and 4 spaces for indented code lines?

**Comment by kzidane** [comment]
Yup. Tested, and looks good!
