### ISSUE TITLE
when receiving input from pipe, output the input in addition to helping

### ISSUE THREAD

**Issue by dmalan** [cs50/help50#250]
Incorrect in old version (and new):

<img width="1277" alt="screen shot 2017-06-24 at 2 49 01 pm" src="https://user-images.githubusercontent.com/788678/27511149-55ed6a88-58ec-11e7-9f3f-781212e58944.png">

Piping, a la `clang foo.c |& help50` should behave just like when running `help50 clang foo.c`.

**Comment by crossroads1112** [comment]
Fixed in the new version. Worth noting though that we can't control the buffering from a process that is piped in.

**Comment by crossroads1112** [comment]
Additionally, there's no way to ensure colored output when input is piped in. Many programs (e.g. clang) will automatically disable colored output when they detect they're not writing to a TTY.

**Comment by dmalan** [comment]
np on piping, but `help50 a.out` should definitely preserve!

**Comment by crossroads1112** [comment]
Addressed in 2af4686
