### ISSUE TITLE
error: called object type 'int' is not a function or function pointer

### ISSUE THREAD

**Issue by Xia-learnstocode** [cs50/help50#268]
`$ help50 make valid_triangle1
clang -fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wshadow    valid_triangle1.c  -lcrypt -lcs50 -lm -o valid_triangle1
valid_triangle1.c:15:38: error: called object type 'int' is not a function or
      function pointer
    if ((x + y <= z) || (x + z <= y) (y + z <= x))
                        ~~~~~~~~~~~~ ^
1 error generated.
make: *** [valid_triangle1] Error 1

Sorry, not sure how to help (yet) with this one!`

**Comment by dmalan** [comment]
Looks like you're missing another || in there!

djm
