### ISSUE TITLE
Error "invalid syntax" when running help50

### ISSUE THREAD

**Issue by NCC1701M** [cs50/help50#274]
I have installed help50 on a Ubuntu  16.4 Windows Subsystem for Linux with the command `pip install help50` but when I run for example `help50 make buggy0` it shows the following message:
```
File "/home/mike/.local/bin/help50", line 39
    proc = pexpect.spawn(f"bash -c \"{' '.join(shlex.quote(word) for word in args.command)}\"", env=os.environ)
                                                                                             ^
SyntaxError: invalid syntax
```

Do I need a specific version of python?

My actual version is `Python 2.7.15+`

**Comment by pr0grammer99** [comment]
I have the same problem. I am running Ubuntu 19.04. I have tried installing with both pip and pip3.

**Comment by kzidane** [comment]
I'm afraid `help50` requires Python 3.6 or above!
