### ISSUE TITLE
pexpect buggy on Linux

### ISSUE THREAD

**Issue by coderigo17** [cs50/help50#275]
https://github.com/pexpect/pexpect/issues/120

**Comment by coderigo17** [comment]
When the program segfaults, pexpect will sometimes fail to catch the last line of output.

**Comment by RhFortuna** [comment]
This issue is about that?:

"ERROR: Cannot uninstall 'pexpect'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall."

**Comment by kzidane** [comment]
pexpect is no longer a dependency of help50.

**Comment by RhFortuna** [comment]
I still get the same error.

```
sudo -H pip install -U help50
...
Installing collected packages: pexpect, lib50, help50
  Attempting uninstall: pexpect
    Found existing installation: pexpect 4.2.1
ERROR: Cannot uninstall 'pexpect'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

```
pip search help50
help50 (3.0.1)
```

**Comment by kzidane** [comment]
Looks like `pexpect` is still required by a dependency of `help50`. Did you happen install `pexpect` on your system using your package manager before by chance? Have you tried https://stackoverflow.com/a/53807588/1797347?

**Comment by RhFortuna** [comment]
No. I found out that python3-pexpect is a dependency of catfish and mugshot, standard Xubuntu system applications.
