### ISSUE TITLE
Submission Query

### ISSUE THREAD

**Issue by Nikitha-V** [cs50/help50#284]
How do we submit the mario assignments when we have already submitted the 1st and want to submit the 2nd too?

**Comment by tommylenz** [comment]
I guess you are speaking of mario less and mario more, am I right? If you already coded your mario more code than simply submit it using [the command shown at the very bottom of your problem's page](https://cs50.harvard.edu/x/2020/psets/1/mario/more/#how-to-submit), in this case `submit50 cs50/problems/2020/x/mario/more`! Don't worry, you won't override your first code's submission - the command specifies your code as the second mario problem (more comfortable version).
