### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement lib50<4,>=2.1 (from help50)

### ISSUE THREAD

**Issue by RhFortuna** [cs50/help50#287]
I upgraded help50 to 3.0.2 but the lib50 is 2.0.9 and it's up-to-date.

`ERROR: Could not find a version that satisfies the requirement lib50<4,>=2.1 (from help50) (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9)
ERROR: No matching distribution found for lib50<4,>=2.1 (from help50)`

pip 20.2.4
Python 3.6.9

**Comment by kzidane** [comment]
Thanks for catching that! Should be fixed now.
