### ISSUE TITLE
shadow declaration clang error

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/help50#3]
Might want a "shadow declaration" help?  If, for example, the student uses a comma rather than a semicolon in their for loop:  `for (int i = 0, i < d; i++)`, clang will spit out: `error: declaration shadows a local variable [-Werror,-Wshadow]`

**Comment by curiouskiwi** [comment]
That typo would also give this error: `expected ';' in 'for' statement specifier` which has been added to help50 so probably not the best example.  Here's another example I've seen:
```

#include <cs50.h>
#include <stdio.h>

int main(void)
{
    int height = 0;
    do
    {
        int height = get_int();
        printf("you gave me %d\n", height);
    }
    while (height > 23);
}
```

Make will return:
 ```
shadow.c:9:13: error: declaration shadows a local variable [-Werror,-Wshadow]
        int height = get_int();
            ^
shadow.c:6:9: note: previous declaration is here
    int height = 0;
        ^
1 error generated.
make: *** [shadow] Error 1
```

**Comment by brianyu28** [comment]
Added as of https://github.com/cs50/help50/commit/9a344a3672307a04b49a65f19af996477ee67a57

**Comment by dmalan** [comment]
Thanks, @curiouskiwi, @brianyu28!
