### ISSUE TITLE
Best way to handle "expected expression"?

### ISSUE THREAD

**Issue by brianyu28** [cs50/help50#39]
@dmalan, can I get your thoughts on this? `error: expected expression` has come up multiple times on `/review` (`11`, `76`, `157`, `228`). The error message is so general, though, that each of the four cases that have triggered it so far have been very different, making it difficult to write a good matcher for. Have any ideas on how to best handle this error?

**Comment by dmalan** [comment]
Hm, that's tricky. It's a pretty generic message. For now, want to add a simple response that simply encourages students to focus on the particular line number? E.g., "Not quite sure how to help, but focus your attention on line {} of `{}`!"
