### ISSUE TITLE
Code Setup issue

### ISSUE THREAD

**Issue by Yashwanthv21** [cs50/help50#53]
After installing docker and cloning the repository.
**docker-compose build** giving errors 
`ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
`
I tried fixing it, and  found that, Ubuntu does not support docker version 2. 
I use ubuntu 16.04.
docker-compose version 1.5.2 and it says its already the latest when i run update command.

Do everyone here have docker version 2 or am i doing something wrong?

**Comment by dmalan** [comment]
Ah, try updating `docker-compose` per https://docs.docker.com/compose/install/. (On Mac OS and Windows, Docker Engine includes the most recent version, but not on Ubuntu it seems.)

**Comment by Yashwanthv21** [comment]
Yes this works. :)
I came across this page previously but clicked on ubuntu on the top.
