### ISSUE TITLE
No help50 message for runtime "Floating point exception"

### ISSUE THREAD

**Issue by adamzu** [cs50/help50#58]
Could we add a useful message for such an error? Maybe something like: "Are you performing any possibly illegal mathematical operations (i.e. dividing by zero)?"

**Comment by dmalan** [comment]
@adamzu can you add sample code that triggers that error? And on what platform did you execute it? I get the below on Ubuntu 14.04, for instance:

```c
#include <stdio.h>

int main(void)
{
    printf("%f\n", 1.0 / 0);
}
```

```
$ clang foo.c
$ ./a.out
inf
```

**Comment by brianyu28** [comment]
This should generate it:

```
#include <stdio.h>

int main(void)
{
    int x = 0;
    printf("%d\n", 28 % x);
}
```

We don't currently have any matchers for runtime errors. @dmalan, will `help50` be able to process runtime error output even if the program has previously prompted the user for input? Also, thoughts on what file to put these in? Our convention of `foo.py` where `foo` is the name of the program generating the error likely won't work here.

**Comment by adamzu** [comment]
yeah I did something like this:
`int main(void)
{
    int x = 24;
    for(int i = x; i >= 0; i--){
        int quotient = x / i;
        printf("%d/n", quotient);
    }
}`

**Comment by dmalan** [comment]
Thanks. Yup, `help50` supports interactive use. E.g.:

```c
#include <cs50.h>
#include <stdio.h>

int main(void)
{
    printf("int: ");
    int x = get_int();
    printf("%d\n", 28 % x);
}
```

```
$ make foo
$ help50 ./foo
int: 0
Sorry, not sure how to help!
```

@brianyu28 maybe just call this matcher `a.out.py` or such, so we remember it's generic?

**Comment by adamzu** [comment]
yeah the compiler catches explicit divides by zero (i.e. int x = 5 / 0; – help50 doesn't have an interpretation of those either but the compiler error is pretty self-explanatory), but not the implicit ones.

```
debug.c:16:11: error: division by zero is undefined [-Werror,-Wdivision-by-zero]
    x = 5 / 0;
          ^ ~
1 error generated.
```
